[functions]
directory = "netlify/functions"

[[headers]]
  for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/"
  to = "https://netlify-blob.netlify.app/"
  status = 200
  force = true
  headers = {X-From = "Netlify"}